spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cosmos-database.ckfgb4giigsr.ap-northeast-2.rds.amazonaws.com/cosmos_db?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: cosmos
    password: cosmos123!